name: Release

on:
  release:
    types: [published]

jobs:
  package-mac:
    runs-on: macos-latest
    if: ${{ !contains(github.event.release.tag_name, '-alpha') && !contains(github.event.release.tag_name, '-beta') }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: mkdir -p release
      - run: npm run package:mac
      - run: ls -lah release/

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.dmg
            release/*.zip
            release/*.blockmap
            release/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package-linux:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.release.tag_name, '-alpha') && !contains(github.event.release.tag_name, '-beta') }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: sudo apt-get update
      - run: sudo apt-get install -y libfuse2 rpm
      - run: npm ci
      - run: npm run build
      - run: mkdir -p release
      - run: npm run package:linux
      - run: ls -lah release/

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.AppImage
            release/*.deb
            release/*.rpm
            release/*.tar.gz
            release/*.tar.xz
            release/*.blockmap
            release/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}